### ISSUE TITLE
add reference for Phoenix CubeSat Flight Software to architecture

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/mission-conops#105]
as per #22, we should add a reference for https://phxcubesat.asu.edu/subsystems/flight-software to support #122 

Should be a YAML file formatted as a [reference](https://github.com/Mach30/m30ml#reference) in the `architecture/0-References` directory

**Comment by kchiu002** [comment]
Is this issue still relevant or has it been overcome by events (OBE).

**Comment by capsulecorplab** [comment]
Closing issue. I don't actually remember why we originally opened this issue
