### ISSUE TITLE
rename components

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/mission-conops#168]
Components specific to Sealion mission should be renamed appropriately

**Comment by BhagatjiJimesh** [comment]
**1. sealion-mission-cubesat-components**
-   >sealion-telecommunication-antenna
-   >sealion-communication-module
-   >sealion-attitude-and-orbital-determination-system-sensors
-   >sealion-power-module
         >battery-package
         >eps-and-interface-board
-   >sealion-obc-board
-   >sealion-mission-payloads
         >odu-deco-paylaod
         >cga-payload
-   >sealion-mission-structure

**2. sealion-mission-ground-station**
-   >odu-mae-ground-station
-   >virginia-tech-ground-station

**Comment by capsulecorplab** [comment]
> **1. sealion-mission-cubesat-components**
> 
> * > sealion-telecommunication-antenna
> * > sealion-communication-module
> * > sealion-attitude-and-orbital-determination-system-sensors
> * > sealion-power-module
>   > >battery-package
>   > >eps-and-interface-board
> * > dilophosaurus-operating-system
> * > sealion-mission-payloads
>   > >odu-deco-paylaod
>   > >cga-payload
> * > sealion-mission-structure
> 
> **2. sealion-mission-ground-station**
> 
> * > odu-mae-ground-station
> * > virginia-tech-ground-station

I would shorten `sealion-mission-cubesat-components` to `sealion-mission-cubesat` and `sealion-attitude-and-orbital-determination-system-sensors` to `sealion-aods-sensors`, where the description would spell out the full human readable name, **Sealion Attitude and Orbital Determination System Sensors**, and nest `dilophosaurus-operating-system` as a subcomponent of `sealion-obc` that also includes the COTS obc. Otherwise, looks good
