### ISSUE TITLE
specify components of a cubesat

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/mission-conops#23]
i.e., sub-components directly owned by the `cubesat` should be specified as per [DOF-Component](https://mach30.github.io/dof/#_component) definition

Each cubesat subcomponent should:
- [ ] subside in the `components/cubesat/components` directory
- [ ] each component should have a package.json, specifying at minimum:
  - [ ] name, styled as `dash-separated-lower-case`
  - [ ] description
  - [ ] version number

**Comment by capsulecorplab** [comment]
blocked on #81

**Comment by paclark5** [comment]
Here is a current list in progress

Structure
Battery
Battery Board
OBC
Dock
Dev Board
UHF Receiver
S-Band Receiver
Cube Torquer
Cube Coil
Magnetometer
Accelerometer
GPS
Sun Sensor
DeCo
VIR-S
Impedence Probe

**Comment by capsulecorplab** [comment]
see https://github.com/modelb-llc/trrs-wssm/ for example

**Comment by kchiu002** [comment]
Components from Updated PDR:

- Structure (Custom)
- Battery (LCF-137)
- EPS & Interface Board (Custom)
- OBC (includes a gyro and magnetometer) (NanoMind A3200)
- Dock (NanoDoc DMC-3)
- UHF Transceiver (NanoCom AX100)
- S-Band Transceiver (NanoCom AX2150)
- Magnetometer (HMR2300-D21-232)
- IMU (Analog Devices ADIS16400BMLZ)
- GPS (NovAtel OEM-719)
- Sun Sensor (FSS100)
- Deco (Custom)
- VIR-S (Custom)
- Impedence Probe (Custom)

**Comment by BhagatjiJimesh** [comment]
I am planning for the following structure for the components. 

1. Structure (Custom)
2. EPS & Interface Board (Custom)
3. Battery Package (LCF-137)
- EaglePicher LCF-137
- Battery Structure
4. OBC 
- NanoMind A3200 (including IMU)
- NanoDoc DMC-3
5. Communication Module
- UHF Transceiver (NanoCom AX100)
- S-Band Transceiver (NanoCom AX2150)
6. Antenna
- UHF Antenna (custom)
- S-Band Antenna (??)
7. AODS Sensors
- Magnetometer (HMR2300-D21-232)
- IMU (Analog Devices ADIS16400BMLZ)
- GPS (NovAtel OEM-719)
- Sun Sensor (FSS100)
8. Payload
- Deco (Custom)
- VIR-S (Custom)
- Impedence Probe (Custom)

**Comment by capsulecorplab** [comment]
closed as per #135
