### ISSUE TITLE
Add stakeholder need for adhering to CubeSat standards as a Primary Mission Objective

### ISSUE THREAD

**Issue by Robb1994** [ODU-CGA-CubeSat/mission-conops#56]
Mission Requirement,
_The SeaLion mission shall adhere to CubeSat standards as per CDS Rev. 13_, 
is specified as a primary mission requirement in Mission Requirements document.

This issue entails adding the aforementioned mission objective as a [stakeholder need](https://github.com/Mach30/m30ml#stakeholder-need) with a relative link to the CubeSat Design Specification in its `derivedFrom` field (see #60)

**Comment by capsulecorplab** [comment]
I think this is a worth while addition to the current list of [stakeholder needs](https://odu-cga-cubesat.github.io/mission-conops/#_stakeholder_needs)
