### ISSUE TITLE
Specify data structure for a "satellite health" packet

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/mission-conops#80]
As per https://github.com/ODU-CGA-CubeSat/flight-software/discussions/39#discussioncomment-1083429, we should specify a [data structure](https://github.com/Mach30/m30ml#data-structures) for a _satellite health_ data packet to be viewed by a ground station operator.

- [ ] should be documented as [data structure](https://github.com/Mach30/m30ml#data-structures) as a `.yaml` file in the `architecture/3-DataStructures/` directory
- [ ] should reference one or more user stories and/or stakeholder needs under `derivedFrom`

**Comment by Robb1994** [comment]
The “satellite health” packet described below will eventually become the content in the TT&C specifications document, which we will need to developed.

Safehold mode telemetry format:

	IMU X 
	IMU Y 
	IMU Z 
	IMU Temperature
	Battery voltage (reports percentage of total power life, if possible)
	Battery current
	Battery bus current
	Battery current direction (Comment: Not sure what this is referring to or if we care to know?) 
	Battery temperature
	Battery 12-V bus current (Comment: Correct number of bus and voltages listed?)
	Battery 5-V bus current 
	Battery 3.3-V bus current
	Transmitter current
	Receiver current
	Time stamp (bits: year, month, day, hour, minute, second)
	Boot count
	Boot time (last boot)
	On-board computer (OBC) temperature
	Processor temperature (Comment: Is this the same as the OBC or different? This question might be for Dr. Asundi)
	Operational status: of equipment where each will indicate if a particular functional mode is either selected or deselected (Space Systems Engineering 14th Ed.). Comment: We may not be able to be determined this until the Mission CONOPS is completed
	Redundancy status: reports each relevant relay or switch with a set of contacts to provide a status bit. (Space Systems Engineering 14th Ed.) Comment: We will have an RBF switch but unsure if we would care to know its status or not
	Attitude Data: Satellite Angular rates (Space Systems Engineering 14th Ed.) Comment: Would the IMU data capture everything we would need for the ADS?
	What else would we want to monitor for satellite health?

Reference: 
SwampSat - 10A1DD0501 Telemetry format (rev 0), Table 2.2 pg. 7
Folder path on Microsoft Teams: General> Design Document> Sample Design Document
Textbook - Space Systems Engineering 14th Ed.
